name: SecureCoinAPI
main: space\yurisi\SecureCoinAPI\SecureCoinAPI
author: yurisi
version: 1.0.0
api: 4.0.0
permissions:
  space.yurisi.SecureCoinAPI.addcoin:
    default: op
  space.yurisi.SecureCoinAPI.coinhistory:
    default: op
  space.yurisi.SecureCoinAPI.givecoin:
    default: true
  space.yurisi.SecureCoinAPI.mycoin:
    default: true
  space.yurisi.SecureCoinAPI.seecoin:
    default: true
  space.yurisi.SecureCoinAPI.setcoin:
    default: op
  space.yurisi.SecureCoinAPI.takecoin:
    default: op